/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GlowSkin AI API specification
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AnalyzeSkinRequest,
  AnalyzeSkinResponse,
  EnvironmentalRiskRequest,
  EnvironmentalRiskResponse,
  ErrorResponse,
  GenerateTreatmentRequest,
  HealthStatus,
  SkinAnalysisRecord,
  SkinHabitCoachRequest,
  SkinHabitCoachResponse,
  TreatmentPlan,
  VoiceDermatologistRequest,
  VoiceDermatologistResponse,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Accepts a base64 image, runs skin analysis, returns detected issues and health score
 * @summary Analyze skin image
 */
export const getAnalyzeSkinUrl = () => {
  return `/api/analyze-skin`;
};

export const analyzeSkin = async (
  analyzeSkinRequest: AnalyzeSkinRequest,
  options?: RequestInit,
): Promise<AnalyzeSkinResponse> => {
  return customFetch<AnalyzeSkinResponse>(getAnalyzeSkinUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(analyzeSkinRequest),
  });
};

export const getAnalyzeSkinMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof analyzeSkin>>,
    TError,
    { data: BodyType<AnalyzeSkinRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof analyzeSkin>>,
  TError,
  { data: BodyType<AnalyzeSkinRequest> },
  TContext
> => {
  const mutationKey = ["analyzeSkin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof analyzeSkin>>,
    { data: BodyType<AnalyzeSkinRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return analyzeSkin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnalyzeSkinMutationResult = NonNullable<
  Awaited<ReturnType<typeof analyzeSkin>>
>;
export type AnalyzeSkinMutationBody = BodyType<AnalyzeSkinRequest>;
export type AnalyzeSkinMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Analyze skin image
 */
export const useAnalyzeSkin = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof analyzeSkin>>,
    TError,
    { data: BodyType<AnalyzeSkinRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof analyzeSkin>>,
  TError,
  { data: BodyType<AnalyzeSkinRequest> },
  TContext
> => {
  return useMutation(getAnalyzeSkinMutationOptions(options));
};

/**
 * Send detected skin issues to Bedrock Nova Lite and get a structured treatment plan
 * @summary Generate AI treatment plan
 */
export const getGenerateTreatmentUrl = () => {
  return `/api/generate-treatment`;
};

export const generateTreatment = async (
  generateTreatmentRequest: GenerateTreatmentRequest,
  options?: RequestInit,
): Promise<TreatmentPlan> => {
  return customFetch<TreatmentPlan>(getGenerateTreatmentUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(generateTreatmentRequest),
  });
};

export const getGenerateTreatmentMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateTreatment>>,
    TError,
    { data: BodyType<GenerateTreatmentRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateTreatment>>,
  TError,
  { data: BodyType<GenerateTreatmentRequest> },
  TContext
> => {
  const mutationKey = ["generateTreatment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateTreatment>>,
    { data: BodyType<GenerateTreatmentRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return generateTreatment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateTreatmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateTreatment>>
>;
export type GenerateTreatmentMutationBody = BodyType<GenerateTreatmentRequest>;
export type GenerateTreatmentMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Generate AI treatment plan
 */
export const useGenerateTreatment = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateTreatment>>,
    TError,
    { data: BodyType<GenerateTreatmentRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof generateTreatment>>,
  TError,
  { data: BodyType<GenerateTreatmentRequest> },
  TContext
> => {
  return useMutation(getGenerateTreatmentMutationOptions(options));
};

/**
 * Fetches weather/pollution data for a city and generates a 7-day skin risk forecast
 * @summary Get environmental skin risk forecast
 */
export const getGetEnvironmentalRiskUrl = () => {
  return `/api/environmental-risk`;
};

export const getEnvironmentalRisk = async (
  environmentalRiskRequest: EnvironmentalRiskRequest,
  options?: RequestInit,
): Promise<EnvironmentalRiskResponse> => {
  return customFetch<EnvironmentalRiskResponse>(getGetEnvironmentalRiskUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(environmentalRiskRequest),
  });
};

export const getGetEnvironmentalRiskMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getEnvironmentalRisk>>,
    TError,
    { data: BodyType<EnvironmentalRiskRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getEnvironmentalRisk>>,
  TError,
  { data: BodyType<EnvironmentalRiskRequest> },
  TContext
> => {
  const mutationKey = ["getEnvironmentalRisk"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getEnvironmentalRisk>>,
    { data: BodyType<EnvironmentalRiskRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return getEnvironmentalRisk(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetEnvironmentalRiskMutationResult = NonNullable<
  Awaited<ReturnType<typeof getEnvironmentalRisk>>
>;
export type GetEnvironmentalRiskMutationBody =
  BodyType<EnvironmentalRiskRequest>;
export type GetEnvironmentalRiskMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Get environmental skin risk forecast
 */
export const useGetEnvironmentalRisk = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getEnvironmentalRisk>>,
    TError,
    { data: BodyType<EnvironmentalRiskRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof getEnvironmentalRisk>>,
  TError,
  { data: BodyType<EnvironmentalRiskRequest> },
  TContext
> => {
  return useMutation(getGetEnvironmentalRiskMutationOptions(options));
};

/**
 * Accepts text from speech-to-text, sends to Bedrock Nova Lite, returns answer text
 * @summary Voice dermatologist Q&A
 */
export const getVoiceDermatologistUrl = () => {
  return `/api/voice-dermatologist`;
};

export const voiceDermatologist = async (
  voiceDermatologistRequest: VoiceDermatologistRequest,
  options?: RequestInit,
): Promise<VoiceDermatologistResponse> => {
  return customFetch<VoiceDermatologistResponse>(getVoiceDermatologistUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(voiceDermatologistRequest),
  });
};

export const getVoiceDermatologistMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof voiceDermatologist>>,
    TError,
    { data: BodyType<VoiceDermatologistRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof voiceDermatologist>>,
  TError,
  { data: BodyType<VoiceDermatologistRequest> },
  TContext
> => {
  const mutationKey = ["voiceDermatologist"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof voiceDermatologist>>,
    { data: BodyType<VoiceDermatologistRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return voiceDermatologist(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type VoiceDermatologistMutationResult = NonNullable<
  Awaited<ReturnType<typeof voiceDermatologist>>
>;
export type VoiceDermatologistMutationBody =
  BodyType<VoiceDermatologistRequest>;
export type VoiceDermatologistMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Voice dermatologist Q&A
 */
export const useVoiceDermatologist = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof voiceDermatologist>>,
    TError,
    { data: BodyType<VoiceDermatologistRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof voiceDermatologist>>,
  TError,
  { data: BodyType<VoiceDermatologistRequest> },
  TContext
> => {
  return useMutation(getVoiceDermatologistMutationOptions(options));
};

/**
 * Uses detected skin issues and environmental data to generate a daily skincare plan
 * @summary Generate personalized daily skin habit plan
 */
export const getSkinHabitCoachUrl = () => {
  return `/api/skin-habit-coach`;
};

export const skinHabitCoach = async (
  skinHabitCoachRequest: SkinHabitCoachRequest,
  options?: RequestInit,
): Promise<SkinHabitCoachResponse> => {
  return customFetch<SkinHabitCoachResponse>(getSkinHabitCoachUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(skinHabitCoachRequest),
  });
};

export const getSkinHabitCoachMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof skinHabitCoach>>,
    TError,
    { data: BodyType<SkinHabitCoachRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof skinHabitCoach>>,
  TError,
  { data: BodyType<SkinHabitCoachRequest> },
  TContext
> => {
  const mutationKey = ["skinHabitCoach"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof skinHabitCoach>>,
    { data: BodyType<SkinHabitCoachRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return skinHabitCoach(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SkinHabitCoachMutationResult = NonNullable<
  Awaited<ReturnType<typeof skinHabitCoach>>
>;
export type SkinHabitCoachMutationBody = BodyType<SkinHabitCoachRequest>;
export type SkinHabitCoachMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Generate personalized daily skin habit plan
 */
export const useSkinHabitCoach = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof skinHabitCoach>>,
    TError,
    { data: BodyType<SkinHabitCoachRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof skinHabitCoach>>,
  TError,
  { data: BodyType<SkinHabitCoachRequest> },
  TContext
> => {
  return useMutation(getSkinHabitCoachMutationOptions(options));
};

/**
 * @summary List past skin analyses
 */
export const getListAnalysesUrl = () => {
  return `/api/analyses`;
};

export const listAnalyses = async (
  options?: RequestInit,
): Promise<SkinAnalysisRecord[]> => {
  return customFetch<SkinAnalysisRecord[]>(getListAnalysesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAnalysesQueryKey = () => {
  return [`/api/analyses`] as const;
};

export const getListAnalysesQueryOptions = <
  TData = Awaited<ReturnType<typeof listAnalyses>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAnalyses>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAnalysesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAnalyses>>> = ({
    signal,
  }) => listAnalyses({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAnalyses>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAnalysesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAnalyses>>
>;
export type ListAnalysesQueryError = ErrorType<unknown>;

/**
 * @summary List past skin analyses
 */

export function useListAnalyses<
  TData = Awaited<ReturnType<typeof listAnalyses>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAnalyses>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAnalysesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
