/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GlowSkin AI API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

/**
 * Optional user-selected skin type
 * @nullable
 */
export type AnalyzeSkinRequestSkinType =
  | (typeof AnalyzeSkinRequestSkinType)[keyof typeof AnalyzeSkinRequestSkinType]
  | null;

export const AnalyzeSkinRequestSkinType = {
  Dry: "Dry",
  Oily: "Oily",
  Combination: "Combination",
  Balanced: "Balanced",
} as const;

export interface AnalyzeSkinRequest {
  /** Base64-encoded image data (without data URL prefix) */
  imageBase64: string;
  /**
   * Optional user-selected skin type
   * @nullable
   */
  skinType?: AnalyzeSkinRequestSkinType;
}

export type SkinIssueSeverity =
  (typeof SkinIssueSeverity)[keyof typeof SkinIssueSeverity];

export const SkinIssueSeverity = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export interface SkinIssue {
  name: string;
  severity: SkinIssueSeverity;
  confidence: number;
}

export interface AnalyzeSkinResponse {
  analysisId: number;
  detectedIssues: SkinIssue[];
  /** 0–100 skin health score */
  healthScore: number;
  /** Estimated recovery days */
  recoveryDays: number;
  /** Label describing the score range */
  scoreLabel: string;
}

export interface GenerateTreatmentRequest {
  /** @nullable */
  analysisId?: number | null;
  detectedIssues: string[];
  /** @nullable */
  skinType?: string | null;
}

export interface RecommendedProducts {
  faceWash: string;
  moisturizer: string;
  sunscreen: string;
  treatmentCream: string;
}

export interface TreatmentPlan {
  lifestyleAdvice: string[];
  morningRoutine: string[];
  nightRoutine: string[];
  naturalTreatments: string[];
  homeRemedy: string;
  recommendedProducts: RecommendedProducts;
}

export interface EnvironmentalRiskRequest {
  city: string;
  detectedIssues?: string[];
}

export type DayForecastRiskLevel =
  (typeof DayForecastRiskLevel)[keyof typeof DayForecastRiskLevel];

export const DayForecastRiskLevel = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export interface DayForecast {
  day: number;
  date: string;
  riskLevel: DayForecastRiskLevel;
  mainRisk: string;
  advice: string;
  /** @nullable */
  uvIndex?: number | null;
  /** @nullable */
  humidity?: number | null;
  /** @nullable */
  temperature?: number | null;
  /** @nullable */
  pm25?: number | null;
}

export interface CurrentConditions {
  uvIndex: number;
  humidity: number;
  temperature: number;
  /** @nullable */
  pm25?: number | null;
  description: string;
}

export interface EnvironmentalRiskResponse {
  city: string;
  currentConditions: CurrentConditions;
  forecast: DayForecast[];
  preventiveAdvice: string[];
}

export interface VoiceDermatologistRequest {
  /** The user's skincare question (from speech-to-text or typed) */
  question: string;
  /**
   * Optional context from previous scan results
   * @nullable
   */
  context?: string | null;
}

export interface VoiceDermatologistResponse {
  answer: string;
  followUpQuestions: string[];
}

export interface SkinHabitCoachRequest {
  detectedIssues: string[];
  environmentalRisks?: string[];
  /** @nullable */
  skinType?: string | null;
}

export interface RoutineStep {
  step: string;
  /** @nullable */
  reason?: string | null;
}

export interface SkinHabitCoachResponse {
  morningRoutine: RoutineStep[];
  afternoonProtection: RoutineStep[];
  nightRoutine: RoutineStep[];
  healthyHabits: string[];
}

export interface SkinAnalysisRecord {
  analysisId: number;
  healthScore: number;
  detectedIssues: string[];
  recoveryDays: number;
  createdAt: string;
}
